import {
  RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_ID,
  RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_JSON_PATH,
  RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_MEDIA_TYPE,
  RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_VERSION
} from './runtime-status-contract-artifact-metadata'
import { RUNTIME_STATUS_PORTING_CONTRACT_DOMAIN_ID } from './runtime-status-contract-domain-id'
import { RUNTIME_STATUS_PORTING_CONTRACT_PARAMS } from './runtime-status-contract-params'
import { RUNTIME_STATUS_PORTING_CONTRACT_SCHEMA_VERSION } from './runtime-status-contract-schema-version'
import {
  RUNTIME_STATUS_PORTING_ARRAY_CONSTRAINTS,
  RUNTIME_STATUS_PORTING_NUMERIC_CONSTRAINTS,
  RUNTIME_STATUS_PORTING_STRING_CONSTRAINTS,
  type RuntimeStatusPortingArrayConstraint,
  type RuntimeStatusPortingNumericConstraint,
  type RuntimeStatusPortingStringConstraint
} from './runtime-status-constraints'
import {
  VALID_RUNTIME_GRAPH_STATUSES,
  VALID_RUNTIME_HOST_PLATFORMS
} from './runtime-status-enum-values'
import {
  INVALIDATABLE_RUNTIME_STATUS_PORTING_FIELDS,
  NON_NEGATIVE_INTEGER_RUNTIME_STATUS_PORTING_FIELDS,
  REQUIRED_RUNTIME_STATUS_PORTING_FIELDS,
  VERSIONED_RUNTIME_STATUS_PORTING_FIELDS
} from './runtime-status-field-groups'
import {
  RUNTIME_STATUS_PORTING_JSON_SCHEMA_DRAFT_URI,
  RUNTIME_STATUS_PORTING_JSON_SCHEMA_ID,
  RUNTIME_STATUS_PORTING_JSON_SCHEMA_TITLE
} from './runtime-status-json-schema'
import type { RuntimeStatusPortingField } from './runtime-status-porting-field'

export type RuntimePortingFirstSliceContractDomainId =
  typeof RUNTIME_STATUS_PORTING_CONTRACT_DOMAIN_ID
export type RuntimePortingFirstSliceContractArtifactId =
  typeof RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_ID
export type RuntimePortingFirstSliceContractArtifactMediaType =
  typeof RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_MEDIA_TYPE
export type RuntimePortingFirstSliceContractArtifactVersion =
  typeof RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_VERSION
export type RuntimePortingFirstSliceContractArtifactPath =
  typeof RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_JSON_PATH
export type RuntimePortingFirstSliceContractSchemaVersion =
  typeof RUNTIME_STATUS_PORTING_CONTRACT_SCHEMA_VERSION
export type RuntimePortingFirstSliceContractParams = typeof RUNTIME_STATUS_PORTING_CONTRACT_PARAMS
export type RuntimePortingFirstSliceContractMethod = 'status.get'
export type RuntimePortingFirstSliceContractJsonSchemaDraftUri =
  typeof RUNTIME_STATUS_PORTING_JSON_SCHEMA_DRAFT_URI
export type RuntimePortingFirstSliceContractJsonSchemaId =
  typeof RUNTIME_STATUS_PORTING_JSON_SCHEMA_ID
export type RuntimePortingFirstSliceContractJsonSchemaTitle =
  typeof RUNTIME_STATUS_PORTING_JSON_SCHEMA_TITLE
export type RuntimePortingFirstSliceContractEnumValues = {
  graphStatus: typeof VALID_RUNTIME_GRAPH_STATUSES
  hostPlatform: typeof VALID_RUNTIME_HOST_PLATFORMS
}
export type RuntimePortingFirstSliceContractEnumFields = readonly RuntimeStatusPortingField[]
export type RuntimePortingFirstSliceContractArrayConstraints = Partial<
  Record<RuntimeStatusPortingField, RuntimeStatusPortingArrayConstraint>
>
export type RuntimePortingFirstSliceContractRequiredFields = readonly RuntimeStatusPortingField[]
export type RuntimePortingFirstSliceContractInvalidatableFields =
  readonly RuntimeStatusPortingField[]
export type RuntimePortingFirstSliceContractNonNegativeIntegerFields =
  readonly RuntimeStatusPortingField[]
export type RuntimePortingFirstSliceContractNullableFields = readonly RuntimeStatusPortingField[]
export type RuntimePortingFirstSliceContractNumericConstraints = Partial<
  Record<RuntimeStatusPortingField, RuntimeStatusPortingNumericConstraint>
>
export type RuntimePortingFirstSliceContractStringConstraints = Partial<
  Record<RuntimeStatusPortingField, RuntimeStatusPortingStringConstraint>
>
export type RuntimePortingFirstSliceContractVersionedFields = readonly RuntimeStatusPortingField[]

export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_DOMAIN_ID: RuntimePortingFirstSliceContractDomainId =
  RUNTIME_STATUS_PORTING_CONTRACT_DOMAIN_ID
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_ID: RuntimePortingFirstSliceContractArtifactId =
  RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_ID
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_MEDIA_TYPE: RuntimePortingFirstSliceContractArtifactMediaType =
  RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_MEDIA_TYPE
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_VERSION: RuntimePortingFirstSliceContractArtifactVersion =
  RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_VERSION
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_PATH: RuntimePortingFirstSliceContractArtifactPath =
  RUNTIME_STATUS_PORTING_CONTRACT_ARTIFACT_JSON_PATH
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SCHEMA_VERSION: RuntimePortingFirstSliceContractSchemaVersion =
  RUNTIME_STATUS_PORTING_CONTRACT_SCHEMA_VERSION
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_PARAMS: RuntimePortingFirstSliceContractParams =
  RUNTIME_STATUS_PORTING_CONTRACT_PARAMS
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_METHOD: RuntimePortingFirstSliceContractMethod =
  'status.get'
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_DRAFT_URI: RuntimePortingFirstSliceContractJsonSchemaDraftUri =
  RUNTIME_STATUS_PORTING_JSON_SCHEMA_DRAFT_URI
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_ID: RuntimePortingFirstSliceContractJsonSchemaId =
  RUNTIME_STATUS_PORTING_JSON_SCHEMA_ID
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_TITLE: RuntimePortingFirstSliceContractJsonSchemaTitle =
  RUNTIME_STATUS_PORTING_JSON_SCHEMA_TITLE
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARRAY_CONSTRAINTS: RuntimePortingFirstSliceContractArrayConstraints =
  RUNTIME_STATUS_PORTING_ARRAY_CONSTRAINTS
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ENUM_VALUES: RuntimePortingFirstSliceContractEnumValues =
  {
    graphStatus: VALID_RUNTIME_GRAPH_STATUSES,
    hostPlatform: VALID_RUNTIME_HOST_PLATFORMS
  }
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ENUM_FIELDS: RuntimePortingFirstSliceContractEnumFields =
  Object.keys(RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ENUM_VALUES) as RuntimeStatusPortingField[]
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALIDATABLE_FIELDS: RuntimePortingFirstSliceContractInvalidatableFields =
  INVALIDATABLE_RUNTIME_STATUS_PORTING_FIELDS
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NON_NEGATIVE_INTEGER_FIELDS: RuntimePortingFirstSliceContractNonNegativeIntegerFields =
  NON_NEGATIVE_INTEGER_RUNTIME_STATUS_PORTING_FIELDS
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NULLABLE_FIELDS: RuntimePortingFirstSliceContractNullableFields =
  Object.entries(RUNTIME_STATUS_PORTING_NUMERIC_CONSTRAINTS)
    .filter(([, constraint]) => constraint.nullable)
    .map(([field]) => field as RuntimeStatusPortingField)
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NUMERIC_CONSTRAINTS: RuntimePortingFirstSliceContractNumericConstraints =
  RUNTIME_STATUS_PORTING_NUMERIC_CONSTRAINTS
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_REQUIRED_FIELDS: RuntimePortingFirstSliceContractRequiredFields =
  REQUIRED_RUNTIME_STATUS_PORTING_FIELDS
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_STRING_CONSTRAINTS: RuntimePortingFirstSliceContractStringConstraints =
  RUNTIME_STATUS_PORTING_STRING_CONSTRAINTS
export const RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VERSIONED_FIELDS: RuntimePortingFirstSliceContractVersionedFields =
  VERSIONED_RUNTIME_STATUS_PORTING_FIELDS
