import type {
  RuntimePortingFirstSliceContractAdditionalProperties,
  RuntimePortingFirstSliceContractArrayConstraints,
  RuntimePortingFirstSliceContractArrayFields,
  RuntimePortingFirstSliceContractArtifactId,
  RuntimePortingFirstSliceContractArtifactMediaType,
  RuntimePortingFirstSliceContractArtifactPath,
  RuntimePortingFirstSliceContractArtifactVersion,
  RuntimePortingFirstSliceContractDomainId,
  RuntimePortingFirstSliceContractEnumFields,
  RuntimePortingFirstSliceContractEnumValues,
  RuntimePortingFirstSliceContractInvalidSampleExpectedResult,
  RuntimePortingFirstSliceContractInvalidSamplePath,
  RuntimePortingFirstSliceContractInvalidatableFields,
  RuntimePortingFirstSliceContractJsonSchemaDraftUri,
  RuntimePortingFirstSliceContractJsonSchemaId,
  RuntimePortingFirstSliceContractJsonSchemaPropertyFields,
  RuntimePortingFirstSliceContractJsonSchemaTitle,
  RuntimePortingFirstSliceContractMethod,
  RuntimePortingFirstSliceContractNonNegativeIntegerFields,
  RuntimePortingFirstSliceContractNullableFields,
  RuntimePortingFirstSliceContractNumericConstraints,
  RuntimePortingFirstSliceContractNumericFields,
  RuntimePortingFirstSliceContractParams,
  RuntimePortingFirstSliceContractRequiredFields,
  RuntimePortingFirstSliceContractSampleManifestArtifactJsonPath,
  RuntimePortingFirstSliceContractSampleManifestArtifactId,
  RuntimePortingFirstSliceContractSampleManifestContractArtifactId,
  RuntimePortingFirstSliceContractSampleManifestContractArtifactMediaType,
  RuntimePortingFirstSliceContractSampleManifestContractArtifactPath,
  RuntimePortingFirstSliceContractSampleManifestContractArtifactVersion,
  RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaDraftUri,
  RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaId,
  RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaTitle,
  RuntimePortingFirstSliceContractSampleManifestContractMethod,
  RuntimePortingFirstSliceContractSampleManifestContractSchemaVersion,
  RuntimePortingFirstSliceContractSampleManifestMediaType,
  RuntimePortingFirstSliceContractSampleManifestPath,
  RuntimePortingFirstSliceContractSampleManifestSchemaVersion,
  RuntimePortingFirstSliceContractSampleVerificationCommand,
  RuntimePortingFirstSliceContractSamples,
  RuntimePortingFirstSliceContractSchemaVersion,
  RuntimePortingFirstSliceContractStringConstraints,
  RuntimePortingFirstSliceContractStringFields,
  RuntimePortingFirstSliceContractValidSampleExpectedResult,
  RuntimePortingFirstSliceContractValidSamplePath,
  RuntimePortingFirstSliceContractVersionedFields
} from './runtime-porting-first-slice-contract'
import type {
  RuntimePortingDomain,
  RuntimePortingDomainSummaryArtifactId,
  RuntimePortingDomainSummaryMediaType,
  RuntimePortingDomainSummarySchemaVersion,
  RuntimePortingFirstSliceMethod,
  RuntimePortingFirstSliceRationale,
  RuntimePortingMigrationStrategy,
  RuntimePortingSourceRuntime,
  RuntimePortingTargetRuntime,
  RuntimePortingVerificationCommand
} from './runtime-porting-domains'

export type RuntimePortingDomainSummary = {
  artifactId: RuntimePortingDomainSummaryArtifactId
  mediaType: RuntimePortingDomainSummaryMediaType
  schemaVersion: RuntimePortingDomainSummarySchemaVersion
  migrationStrategy: RuntimePortingMigrationStrategy
  sourceRuntime: RuntimePortingSourceRuntime
  targetRuntime: RuntimePortingTargetRuntime
  verificationCommand: RuntimePortingVerificationCommand
  firstSlice: RuntimePortingDomain
  firstSliceContractDomainId: RuntimePortingFirstSliceContractDomainId
  firstSliceContractArtifactId: RuntimePortingFirstSliceContractArtifactId
  firstSliceContractArtifactMediaType: RuntimePortingFirstSliceContractArtifactMediaType
  firstSliceContractArtifactVersion: RuntimePortingFirstSliceContractArtifactVersion
  firstSliceContractArtifactPath: RuntimePortingFirstSliceContractArtifactPath
  firstSliceContractValidSamplePath: RuntimePortingFirstSliceContractValidSamplePath
  firstSliceContractInvalidSamplePath: RuntimePortingFirstSliceContractInvalidSamplePath
  firstSliceContractValidSampleExpectedResult: RuntimePortingFirstSliceContractValidSampleExpectedResult
  firstSliceContractInvalidSampleExpectedResult: RuntimePortingFirstSliceContractInvalidSampleExpectedResult
  firstSliceContractSamples: RuntimePortingFirstSliceContractSamples
  firstSliceContractSampleVerificationCommand: RuntimePortingFirstSliceContractSampleVerificationCommand
  firstSliceContractSampleManifestPath: RuntimePortingFirstSliceContractSampleManifestPath
  firstSliceContractSampleManifestArtifactId: RuntimePortingFirstSliceContractSampleManifestArtifactId
  firstSliceContractSampleManifestMediaType: RuntimePortingFirstSliceContractSampleManifestMediaType
  firstSliceContractSampleManifestSchemaVersion: RuntimePortingFirstSliceContractSampleManifestSchemaVersion
  firstSliceContractSampleManifestArtifactJsonPath: RuntimePortingFirstSliceContractSampleManifestArtifactJsonPath
  firstSliceContractSampleManifestContractArtifactId: RuntimePortingFirstSliceContractSampleManifestContractArtifactId
  firstSliceContractSampleManifestContractArtifactMediaType: RuntimePortingFirstSliceContractSampleManifestContractArtifactMediaType
  firstSliceContractSampleManifestContractArtifactVersion: RuntimePortingFirstSliceContractSampleManifestContractArtifactVersion
  firstSliceContractSampleManifestContractSchemaVersion: RuntimePortingFirstSliceContractSampleManifestContractSchemaVersion
  firstSliceContractSampleManifestContractJsonSchemaDraftUri: RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaDraftUri
  firstSliceContractSampleManifestContractJsonSchemaId: RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaId
  firstSliceContractSampleManifestContractJsonSchemaTitle: RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaTitle
  firstSliceContractSampleManifestContractMethod: RuntimePortingFirstSliceContractSampleManifestContractMethod
  firstSliceContractSampleManifestContractArtifactPath: RuntimePortingFirstSliceContractSampleManifestContractArtifactPath
  firstSliceContractSchemaVersion: RuntimePortingFirstSliceContractSchemaVersion
  firstSliceContractParams: RuntimePortingFirstSliceContractParams
  firstSliceContractMethod: RuntimePortingFirstSliceContractMethod
  firstSliceContractJsonSchemaDraftUri: RuntimePortingFirstSliceContractJsonSchemaDraftUri
  firstSliceContractJsonSchemaId: RuntimePortingFirstSliceContractJsonSchemaId
  firstSliceContractJsonSchemaTitle: RuntimePortingFirstSliceContractJsonSchemaTitle
  firstSliceContractJsonSchemaPropertyFields: RuntimePortingFirstSliceContractJsonSchemaPropertyFields
  firstSliceContractAdditionalProperties: RuntimePortingFirstSliceContractAdditionalProperties
  firstSliceContractArrayFields: RuntimePortingFirstSliceContractArrayFields
  firstSliceContractArrayConstraints: RuntimePortingFirstSliceContractArrayConstraints
  firstSliceContractEnumFields: RuntimePortingFirstSliceContractEnumFields
  firstSliceContractEnumValues: RuntimePortingFirstSliceContractEnumValues
  firstSliceContractInvalidatableFields: RuntimePortingFirstSliceContractInvalidatableFields
  firstSliceContractNonNegativeIntegerFields: RuntimePortingFirstSliceContractNonNegativeIntegerFields
  firstSliceContractNullableFields: RuntimePortingFirstSliceContractNullableFields
  firstSliceContractNumericFields: RuntimePortingFirstSliceContractNumericFields
  firstSliceContractNumericConstraints: RuntimePortingFirstSliceContractNumericConstraints
  firstSliceContractRequiredFields: RuntimePortingFirstSliceContractRequiredFields
  firstSliceContractStringFields: RuntimePortingFirstSliceContractStringFields
  firstSliceContractStringConstraints: RuntimePortingFirstSliceContractStringConstraints
  firstSliceContractVersionedFields: RuntimePortingFirstSliceContractVersionedFields
  firstSliceRationale: RuntimePortingFirstSliceRationale
  firstSliceMethod: RuntimePortingFirstSliceMethod
  nativeCandidates: readonly RuntimePortingDomain[]
  retainedElectron: readonly RuntimePortingDomain[]
  totalDomainCount: number
  nativeCandidateCount: number
  retainedElectronCount: number
}
