import type {
  RuntimePortingFirstSliceContractAdditionalProperties,
  RuntimePortingFirstSliceContractArrayConstraints,
  RuntimePortingFirstSliceContractArrayFields,
  RuntimePortingFirstSliceContractArtifactId,
  RuntimePortingFirstSliceContractArtifactJsonPath,
  RuntimePortingFirstSliceContractArtifactMediaType,
  RuntimePortingFirstSliceContractArtifactPath,
  RuntimePortingFirstSliceContractArtifactVersion,
  RuntimePortingFirstSliceContractDomainId,
  RuntimePortingFirstSliceContractEnumFields,
  RuntimePortingFirstSliceContractEnumValues,
  RuntimePortingFirstSliceContractInvalidSampleExpectedResult,
  RuntimePortingFirstSliceContractInvalidSamplePath,
  RuntimePortingFirstSliceContractInvalidatableFields,
  RuntimePortingFirstSliceContractJsonSchemaDraftUri,
  RuntimePortingFirstSliceContractJsonSchema,
  RuntimePortingFirstSliceContractJsonSchemaId,
  RuntimePortingFirstSliceContractJsonSchemaPropertyFields,
  RuntimePortingFirstSliceContractJsonSchemaTitle,
  RuntimePortingFirstSliceContractMethod,
  RuntimePortingFirstSliceContractNonNegativeIntegerFields,
  RuntimePortingFirstSliceContractNullableFields,
  RuntimePortingFirstSliceContractNumericConstraints,
  RuntimePortingFirstSliceContractNumericFields,
  RuntimePortingFirstSliceContractParams,
  RuntimePortingFirstSliceContractRequiredFields,
  RuntimePortingFirstSliceContractSampleManifestArtifactJsonPath,
  RuntimePortingFirstSliceContractSampleManifestArtifactId,
  RuntimePortingFirstSliceContractSampleManifestContractArtifactId,
  RuntimePortingFirstSliceContractSampleManifestContractArtifactMediaType,
  RuntimePortingFirstSliceContractSampleManifestContractArtifactPath,
  RuntimePortingFirstSliceContractSampleManifestContractArtifactVersion,
  RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaDraftUri,
  RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaId,
  RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaTitle,
  RuntimePortingFirstSliceContractSampleManifestContractMethod,
  RuntimePortingFirstSliceContractSampleManifestContractParams,
  RuntimePortingFirstSliceContractSampleManifestContractSchemaVersion,
  RuntimePortingFirstSliceContractSampleManifestMediaType,
  RuntimePortingFirstSliceContractSampleManifestPath,
  RuntimePortingFirstSliceContractSampleManifestSamples,
  RuntimePortingFirstSliceContractSampleManifestSchemaVersion,
  RuntimePortingFirstSliceContractSampleManifestVerificationCommand,
  RuntimePortingFirstSliceContractSampleVerificationCommand,
  RuntimePortingFirstSliceContractSamples,
  RuntimePortingFirstSliceContractSchemaVersion,
  RuntimePortingFirstSliceContractStringConstraints,
  RuntimePortingFirstSliceContractStringFields,
  RuntimePortingFirstSliceContractSummary,
  RuntimePortingFirstSliceContractValidSampleExpectedResult,
  RuntimePortingFirstSliceContractValidSamplePath,
  RuntimePortingFirstSliceContractVersionedFields
} from './runtime-porting-first-slice-contract'
import type { RuntimeStatusPortingContractArtifact } from './runtime-status-contract-artifact'
import type {
  RuntimePortingDomain,
  RuntimePortingDomainSummaryArtifactId,
  RuntimePortingDomainSummaryMediaType,
  RuntimePortingDomainSummarySchemaVersion,
  RuntimePortingFirstSliceMethod,
  RuntimePortingFirstSliceRationale,
  RuntimePortingMigrationStrategy,
  RuntimePortingSourceRuntime,
  RuntimePortingTargetRuntime,
  RuntimePortingVerificationCommand
} from './runtime-porting-domains'

export type RuntimePortingDomainSummary = {
  artifactId: RuntimePortingDomainSummaryArtifactId
  mediaType: RuntimePortingDomainSummaryMediaType
  schemaVersion: RuntimePortingDomainSummarySchemaVersion
  migrationStrategy: RuntimePortingMigrationStrategy
  sourceRuntime: RuntimePortingSourceRuntime
  targetRuntime: RuntimePortingTargetRuntime
  verificationCommand: RuntimePortingVerificationCommand
  firstSlice: RuntimePortingDomain
  firstSliceContractDomainId: RuntimePortingFirstSliceContractDomainId
  firstSliceContractArtifact: RuntimeStatusPortingContractArtifact
  firstSliceContractArtifactId: RuntimePortingFirstSliceContractArtifactId
  firstSliceContractArtifactMediaType: RuntimePortingFirstSliceContractArtifactMediaType
  firstSliceContractArtifactVersion: RuntimePortingFirstSliceContractArtifactVersion
  firstSliceContractArtifactPath: RuntimePortingFirstSliceContractArtifactPath
  firstSliceContractArtifactJsonPath: RuntimePortingFirstSliceContractArtifactJsonPath
  firstSliceContractSummary: RuntimePortingFirstSliceContractSummary
  firstSliceContractValidSamplePath: RuntimePortingFirstSliceContractValidSamplePath
  firstSliceContractInvalidSamplePath: RuntimePortingFirstSliceContractInvalidSamplePath
  firstSliceContractValidSampleExpectedResult: RuntimePortingFirstSliceContractValidSampleExpectedResult
  firstSliceContractInvalidSampleExpectedResult: RuntimePortingFirstSliceContractInvalidSampleExpectedResult
  firstSliceContractSamples: RuntimePortingFirstSliceContractSamples
  firstSliceContractSampleCount: number
  firstSliceContractSampleKinds: readonly string[]
  firstSliceContractValidSampleCount: number
  firstSliceContractInvalidSampleCount: number
  firstSliceContractSamplePaths: readonly string[]
  firstSliceContractSampleVerificationCommand: RuntimePortingFirstSliceContractSampleVerificationCommand
  firstSliceContractSampleManifestPath: RuntimePortingFirstSliceContractSampleManifestPath
  firstSliceContractSampleManifestArtifactId: RuntimePortingFirstSliceContractSampleManifestArtifactId
  firstSliceContractSampleManifestMediaType: RuntimePortingFirstSliceContractSampleManifestMediaType
  firstSliceContractSampleManifestSchemaVersion: RuntimePortingFirstSliceContractSampleManifestSchemaVersion
  firstSliceContractSampleManifestArtifactJsonPath: RuntimePortingFirstSliceContractSampleManifestArtifactJsonPath
  firstSliceContractSampleManifestContractArtifactId: RuntimePortingFirstSliceContractSampleManifestContractArtifactId
  firstSliceContractSampleManifestContractArtifactMediaType: RuntimePortingFirstSliceContractSampleManifestContractArtifactMediaType
  firstSliceContractSampleManifestContractArtifactVersion: RuntimePortingFirstSliceContractSampleManifestContractArtifactVersion
  firstSliceContractSampleManifestContractSchemaVersion: RuntimePortingFirstSliceContractSampleManifestContractSchemaVersion
  firstSliceContractSampleManifestContractJsonSchemaDraftUri: RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaDraftUri
  firstSliceContractSampleManifestContractJsonSchemaId: RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaId
  firstSliceContractSampleManifestContractJsonSchemaTitle: RuntimePortingFirstSliceContractSampleManifestContractJsonSchemaTitle
  firstSliceContractSampleManifestContractMethod: RuntimePortingFirstSliceContractSampleManifestContractMethod
  firstSliceContractSampleManifestContractParams: RuntimePortingFirstSliceContractSampleManifestContractParams
  firstSliceContractSampleManifestContractArtifactPath: RuntimePortingFirstSliceContractSampleManifestContractArtifactPath
  firstSliceContractSampleManifestSamples: RuntimePortingFirstSliceContractSampleManifestSamples
  firstSliceContractSampleManifestSampleCount: number
  firstSliceContractSampleManifestSampleKinds: readonly string[]
  firstSliceContractSampleManifestValidSampleCount: number
  firstSliceContractSampleManifestSamplePaths: readonly string[]
  firstSliceContractSampleManifestVerificationCommand: RuntimePortingFirstSliceContractSampleManifestVerificationCommand
  firstSliceContractSchemaVersion: RuntimePortingFirstSliceContractSchemaVersion
  firstSliceContractParams: RuntimePortingFirstSliceContractParams
  firstSliceContractMethod: RuntimePortingFirstSliceContractMethod
  firstSliceContractJsonSchemaDraftUri: RuntimePortingFirstSliceContractJsonSchemaDraftUri
  firstSliceContractJsonSchemaId: RuntimePortingFirstSliceContractJsonSchemaId
  firstSliceContractJsonSchemaTitle: RuntimePortingFirstSliceContractJsonSchemaTitle
  firstSliceContractJsonSchema: RuntimePortingFirstSliceContractJsonSchema
  firstSliceContractJsonSchemaPropertyFields: RuntimePortingFirstSliceContractJsonSchemaPropertyFields
  firstSliceContractJsonSchemaPropertyCount: number
  firstSliceContractAdditionalProperties: RuntimePortingFirstSliceContractAdditionalProperties
  firstSliceContractArrayFields: RuntimePortingFirstSliceContractArrayFields
  firstSliceContractArrayFieldCount: number
  firstSliceContractArrayConstraints: RuntimePortingFirstSliceContractArrayConstraints
  firstSliceContractEnumFields: RuntimePortingFirstSliceContractEnumFields
  firstSliceContractEnumFieldCount: number
  firstSliceContractEnumValues: RuntimePortingFirstSliceContractEnumValues
  firstSliceContractInvalidatableFields: RuntimePortingFirstSliceContractInvalidatableFields
  firstSliceContractInvalidatableFieldCount: number
  firstSliceContractNonNegativeIntegerFields: RuntimePortingFirstSliceContractNonNegativeIntegerFields
  firstSliceContractNonNegativeIntegerFieldCount: number
  firstSliceContractNullableFields: RuntimePortingFirstSliceContractNullableFields
  firstSliceContractNullableFieldCount: number
  firstSliceContractNumericFields: RuntimePortingFirstSliceContractNumericFields
  firstSliceContractNumericFieldCount: number
  firstSliceContractNumericConstraints: RuntimePortingFirstSliceContractNumericConstraints
  firstSliceContractRequiredFields: RuntimePortingFirstSliceContractRequiredFields
  firstSliceContractRequiredFieldCount: number
  firstSliceContractStringFields: RuntimePortingFirstSliceContractStringFields
  firstSliceContractStringFieldCount: number
  firstSliceContractStringConstraints: RuntimePortingFirstSliceContractStringConstraints
  firstSliceContractVersionedFields: RuntimePortingFirstSliceContractVersionedFields
  firstSliceContractVersionedFieldCount: number
  firstSliceRationale: RuntimePortingFirstSliceRationale
  firstSliceMethod: RuntimePortingFirstSliceMethod
  nativeCandidates: readonly RuntimePortingDomain[]
  retainedElectron: readonly RuntimePortingDomain[]
  totalDomainCount: number
  nativeCandidateCount: number
  retainedElectronCount: number
}
