import {
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ADDITIONAL_PROPERTIES,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARRAY_CONSTRAINTS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARRAY_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_ID,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_JSON_PATH,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_MEDIA_TYPE,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_PATH,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_VERSION,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_DOMAIN_ID,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ENUM_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ENUM_VALUES,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALID_SAMPLE_EXPECTED_RESULT,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALID_SAMPLE_PATH,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALIDATABLE_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_DRAFT_URI,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_ID,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_PROPERTY_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_TITLE,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_METHOD,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NON_NEGATIVE_INTEGER_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NULLABLE_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NUMERIC_CONSTRAINTS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NUMERIC_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_PARAMS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_REQUIRED_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_ARTIFACT_ID,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_ARTIFACT_JSON_PATH,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_ARTIFACT_ID,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_ARTIFACT_MEDIA_TYPE,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_ARTIFACT_PATH,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_ARTIFACT_VERSION,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_JSON_SCHEMA_DRAFT_URI,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_JSON_SCHEMA_ID,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_JSON_SCHEMA_TITLE,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_METHOD,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_PARAMS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_SCHEMA_VERSION,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_MEDIA_TYPE,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_PATH,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SAMPLES,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SCHEMA_VERSION,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_VERIFICATION_COMMAND,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_VERIFICATION_COMMAND,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLES,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SCHEMA_VERSION,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_STRING_CONSTRAINTS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_STRING_FIELDS,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SUMMARY,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VALID_SAMPLE_EXPECTED_RESULT,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VALID_SAMPLE_PATH,
  RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VERSIONED_FIELDS
} from './runtime-porting-first-slice-contract'
import type { RuntimePortingDomainSummary } from './runtime-porting-domain-summary'
import {
  getRuntimePortingFirstSliceDomain,
  getRuntimePortingFirstSliceMethod,
  listNativeRuntimePortingCandidates,
  listRetainedElectronRuntimeDomains,
  RUNTIME_PORTING_DOMAINS,
  RUNTIME_PORTING_DOMAIN_SUMMARY_ARTIFACT_ID,
  RUNTIME_PORTING_DOMAIN_SUMMARY_MEDIA_TYPE,
  RUNTIME_PORTING_DOMAIN_SUMMARY_SCHEMA_VERSION,
  RUNTIME_PORTING_FIRST_SLICE_RATIONALE,
  RUNTIME_PORTING_MIGRATION_STRATEGY,
  RUNTIME_PORTING_SOURCE_RUNTIME,
  RUNTIME_PORTING_TARGET_RUNTIME,
  RUNTIME_PORTING_VERIFICATION_COMMAND
} from './runtime-porting-domains'
import { getRuntimeStatusPortingContractArtifact } from './runtime-status-contract-artifact'

export function getRuntimePortingDomainSummary(): RuntimePortingDomainSummary {
  const nativeCandidates = listNativeRuntimePortingCandidates()
  const retainedElectron = listRetainedElectronRuntimeDomains()

  return {
    artifactId: RUNTIME_PORTING_DOMAIN_SUMMARY_ARTIFACT_ID,
    mediaType: RUNTIME_PORTING_DOMAIN_SUMMARY_MEDIA_TYPE,
    schemaVersion: RUNTIME_PORTING_DOMAIN_SUMMARY_SCHEMA_VERSION,
    migrationStrategy: RUNTIME_PORTING_MIGRATION_STRATEGY,
    sourceRuntime: RUNTIME_PORTING_SOURCE_RUNTIME,
    targetRuntime: RUNTIME_PORTING_TARGET_RUNTIME,
    verificationCommand: RUNTIME_PORTING_VERIFICATION_COMMAND,
    firstSlice: getRuntimePortingFirstSliceDomain(),
    firstSliceContractDomainId: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_DOMAIN_ID,
    firstSliceContractArtifact: getRuntimeStatusPortingContractArtifact(),
    firstSliceContractArtifactId: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_ID,
    firstSliceContractArtifactMediaType: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_MEDIA_TYPE,
    firstSliceContractArtifactVersion: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_VERSION,
    firstSliceContractArtifactPath: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_PATH,
    firstSliceContractArtifactJsonPath: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARTIFACT_JSON_PATH,
    firstSliceContractSummary: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SUMMARY,
    firstSliceContractValidSamplePath: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VALID_SAMPLE_PATH,
    firstSliceContractInvalidSamplePath: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALID_SAMPLE_PATH,
    firstSliceContractValidSampleExpectedResult:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VALID_SAMPLE_EXPECTED_RESULT,
    firstSliceContractInvalidSampleExpectedResult:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALID_SAMPLE_EXPECTED_RESULT,
    firstSliceContractSamples: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLES,
    firstSliceContractSampleCount: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLES.length,
    firstSliceContractSampleKinds: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLES.map(
      (sample) => sample.kind
    ),
    firstSliceContractValidSampleCount: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLES.filter(
      (sample) => sample.kind === 'valid'
    ).length,
    firstSliceContractInvalidSampleCount: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLES.filter(
      (sample) => sample.kind === 'invalid'
    ).length,
    firstSliceContractSamplePaths: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLES.map(
      (sample) => sample.path
    ),
    firstSliceContractSampleVerificationCommand:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_VERIFICATION_COMMAND,
    firstSliceContractSampleManifestPath: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_PATH,
    firstSliceContractSampleManifestArtifactId:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_ARTIFACT_ID,
    firstSliceContractSampleManifestMediaType:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_MEDIA_TYPE,
    firstSliceContractSampleManifestSchemaVersion:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SCHEMA_VERSION,
    firstSliceContractSampleManifestArtifactJsonPath:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_ARTIFACT_JSON_PATH,
    firstSliceContractSampleManifestContractArtifactId:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_ARTIFACT_ID,
    firstSliceContractSampleManifestContractArtifactMediaType:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_ARTIFACT_MEDIA_TYPE,
    firstSliceContractSampleManifestContractArtifactVersion:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_ARTIFACT_VERSION,
    firstSliceContractSampleManifestContractSchemaVersion:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_SCHEMA_VERSION,
    firstSliceContractSampleManifestContractJsonSchemaDraftUri:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_JSON_SCHEMA_DRAFT_URI,
    firstSliceContractSampleManifestContractJsonSchemaId:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_JSON_SCHEMA_ID,
    firstSliceContractSampleManifestContractJsonSchemaTitle:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_JSON_SCHEMA_TITLE,
    firstSliceContractSampleManifestContractMethod:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_METHOD,
    firstSliceContractSampleManifestContractParams:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_PARAMS,
    firstSliceContractSampleManifestContractArtifactPath:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_CONTRACT_ARTIFACT_PATH,
    firstSliceContractSampleManifestSamples:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SAMPLES,
    firstSliceContractSampleManifestSampleCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SAMPLES.length,
    firstSliceContractSampleManifestSampleKinds:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SAMPLES.map((sample) => sample.kind),
    firstSliceContractSampleManifestValidSampleCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SAMPLES.filter(
        (sample) => sample.kind === 'valid'
      ).length,
    firstSliceContractSampleManifestInvalidSampleCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SAMPLES.filter(
        (sample) => sample.kind === 'invalid'
      ).length,
    firstSliceContractSampleManifestSamplePaths:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SAMPLES.map((sample) => sample.path),
    firstSliceContractSampleManifestExpectedResults:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_SAMPLES.map(
        (sample) => sample.expectedResult
      ),
    firstSliceContractSampleManifestValidSampleExpectedResult:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VALID_SAMPLE_EXPECTED_RESULT,
    firstSliceContractSampleManifestInvalidSampleExpectedResult:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALID_SAMPLE_EXPECTED_RESULT,
    firstSliceContractSampleManifestVerificationCommand:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SAMPLE_MANIFEST_VERIFICATION_COMMAND,
    firstSliceContractSchemaVersion: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_SCHEMA_VERSION,
    firstSliceContractParams: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_PARAMS,
    firstSliceContractMethod: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_METHOD,
    firstSliceContractJsonSchemaDraftUri:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_DRAFT_URI,
    firstSliceContractJsonSchemaId: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_ID,
    firstSliceContractJsonSchemaTitle: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_TITLE,
    firstSliceContractJsonSchema: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA,
    firstSliceContractJsonSchemaPropertyFields:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_PROPERTY_FIELDS,
    firstSliceContractJsonSchemaPropertyCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_JSON_SCHEMA_PROPERTY_FIELDS.length,
    firstSliceContractAdditionalProperties:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ADDITIONAL_PROPERTIES,
    firstSliceContractArrayFields: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARRAY_FIELDS,
    firstSliceContractArrayFieldCount: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARRAY_FIELDS.length,
    firstSliceContractArrayConstraints: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ARRAY_CONSTRAINTS,
    firstSliceContractEnumFields: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ENUM_FIELDS,
    firstSliceContractEnumFieldCount: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ENUM_FIELDS.length,
    firstSliceContractEnumValues: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_ENUM_VALUES,
    firstSliceContractInvalidatableFields:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALIDATABLE_FIELDS,
    firstSliceContractInvalidatableFieldCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_INVALIDATABLE_FIELDS.length,
    firstSliceContractNonNegativeIntegerFields:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NON_NEGATIVE_INTEGER_FIELDS,
    firstSliceContractNonNegativeIntegerFieldCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NON_NEGATIVE_INTEGER_FIELDS.length,
    firstSliceContractNullableFields: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NULLABLE_FIELDS,
    firstSliceContractNullableFieldCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NULLABLE_FIELDS.length,
    firstSliceContractNumericFields: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NUMERIC_FIELDS,
    firstSliceContractNumericFieldCount: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NUMERIC_FIELDS.length,
    firstSliceContractNumericConstraints: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_NUMERIC_CONSTRAINTS,
    firstSliceContractRequiredFields: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_REQUIRED_FIELDS,
    firstSliceContractRequiredFieldCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_REQUIRED_FIELDS.length,
    firstSliceContractStringFields: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_STRING_FIELDS,
    firstSliceContractStringFieldCount: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_STRING_FIELDS.length,
    firstSliceContractStringConstraints: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_STRING_CONSTRAINTS,
    firstSliceContractVersionedFields: RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VERSIONED_FIELDS,
    firstSliceContractVersionedFieldCount:
      RUNTIME_PORTING_FIRST_SLICE_CONTRACT_VERSIONED_FIELDS.length,
    firstSliceRationale: RUNTIME_PORTING_FIRST_SLICE_RATIONALE,
    firstSliceMethod: getRuntimePortingFirstSliceMethod(),
    nativeCandidates,
    retainedElectron,
    totalDomainCount: RUNTIME_PORTING_DOMAINS.length,
    nativeCandidateCount: nativeCandidates.length,
    retainedElectronCount: retainedElectron.length
  }
}

export function getRuntimePortingDomainSummaryJson(): string {
  return `${JSON.stringify(getRuntimePortingDomainSummary(), null, 2)}\n`
}
